# Generated by Django 5.0.7 on 2024-07-14 16:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='poster',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
