# Generated by Django 5.0.7 on 2024-07-17 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_review'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Review',
        ),
    ]
